"""End-to-end UI test of the app against the live gateway API (sim) and in demo mode."""
import json, sys, time, urllib.request
from playwright.sync_api import sync_playwright
BASE = "http://localhost:8000"; TOK = "123456"; OUT = "/home/claude/mobile/shots/"
ok = []; errs = []
def check(n, c, d=""): ok.append((n, bool(c))); print(("PASS " if c else "FAIL ") + n + ("" if c else f" [{d}]"))
def api(path, method="GET", body=None):
    req = urllib.request.Request(BASE + path, method=method, data=(json.dumps(body).encode() if body is not None else None),
                                 headers={"x-gateway-token": TOK, "content-type": "application/json"})
    return json.loads(urllib.request.urlopen(req).read())

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    pg = ctx.new_page()
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto(BASE + "/"); pg.wait_for_selector("#connForm")
    pg.wait_for_function("document.querySelector('#u') && document.querySelector('#u').value !== ''", timeout=15000)
    check("connect screen prefills the gateway address", pg.input_value("#u") == BASE)
    pg.fill("#t", "000000"); pg.click("#connForm button[type=submit]"); pg.wait_for_timeout(800)
    check("wrong pairing code is reported", "pairing code is wrong" in pg.inner_text("#view"))
    pg.fill("#t", TOK); pg.click("#connForm button[type=submit]"); pg.wait_for_selector("text=Root-zone water")
    pg.screenshot(path=OUT + "01_home_empty.png")
    # advance the replay until the agent issues an irrigate advisory
    api("/api/answers", "POST", {"fields": {"water_source": "canal", "canal_interval_days": 7, "canal_next_day": 2,
                                            "area_ha": 0.2, "pump_flow_lpm": 600, "tariff_per_hour": 40}})
    for _ in range(200):
        api("/api/sim/advance?days=1", "POST", {}); api("/api/sim/reading", "POST", {})
        s = api("/api/status")
        if s["pending"] and s["pending"][0]["action"] == "irrigate": break
    pg.reload(); pg.wait_for_selector("text=Today's advice")
    check("home shows the irrigate advice", "Irrigate" in pg.inner_text(".hero"))
    check("advice badge shown", pg.is_visible("#adviceBadge"))
    pg.screenshot(path=OUT + "02_home_advice.png", full_page=True)
    pg.click("[data-go=advice]"); pg.wait_for_selector("[data-act=approve]")
    txt = pg.inner_text("#view")
    check("advice screen states the approval gate", "pump starts only after you approve" in txt)
    check("advice shows pump time estimate", "min" in txt)
    check("advice shows the rain forecast, labelled simulated", "Rain in the next 24 h" in txt and "simulated" in txt, txt[:400])
    n_before_why = len(api("/api/commands"))
    pg.click("[data-why]"); pg.wait_for_selector("dialog[open] .chip")
    check("why: seven question chips", pg.locator("dialog .chip").count() == 7)
    pg.click("dialog .chip[data-q=amount]"); pg.wait_for_timeout(200)
    a = pg.locator("dialog .msg.a").last.inner_text()
    check("why: 'Why this amount?' answers with the refill and the pump time", "field capacity" in a or "limited" in a, a)
    pg.fill("#whyText", "what if it rains tomorrow?"); pg.press("#whyText", "Enter"); pg.wait_for_timeout(200)
    a = pg.locator("dialog .msg.a").last.inner_text()
    check("why: a typed rain question gets the rain answer", "(What about rain?)" in a, a)
    pg.fill("#whyText", "who won the cricket"); pg.click("#whySend"); pg.wait_for_timeout(200)
    a = pg.locator("dialog .msg.a").last.inner_text()
    check("why: an unrelated question is declined, not guessed", "only answer questions about this advice" in a, a)
    pg.screenshot(path=OUT + "03b_why_chat.png")
    pg.click("#whyClose"); pg.wait_for_timeout(300)
    check("why: asking changed nothing", len(api("/api/commands")) == n_before_why and not pg.is_visible("dialog[open]"))
    pg.screenshot(path=OUT + "03_advice.png", full_page=True)
    n0 = len(api("/api/commands"))
    pg.click("[data-act=approve]"); pg.wait_for_selector("dialog[open]")
    pg.screenshot(path=OUT + "04_approve_dialog.png")
    pg.click("dialog button[value=cancel]"); pg.wait_for_timeout(400)
    check("cancel runs nothing", len(api("/api/commands")) == n0)
    pg.click("[data-act=approve]"); pg.wait_for_selector("dialog[open]"); pg.click("dialog button[value=ok]")
    pg.wait_for_selector("#toast:not([hidden])"); t = pg.inner_text("#toast")
    check("approval confirmed with a pump-run toast", "Pump run recorded" in t, t)
    cm = api("/api/commands")
    check("exactly one command, from the approval", len(cm) == n0 + 1 and cm[0]["origin"] == "approved_advisory")
    pg.screenshot(path=OUT + "05_after_approve.png")
    # next irrigate: reject with reason
    for _ in range(200):
        api("/api/sim/advance?days=1", "POST", {})
        s = api("/api/status")
        if s["pending"] and s["pending"][0]["action"] == "irrigate": break
    pg.click("[data-tab=advice]"); pg.wait_for_selector("[data-act=reject]")
    pg.click("[data-act=reject]"); pg.wait_for_selector("dialog[open]")
    pg.screenshot(path=OUT + "06_reject_dialog.png")
    pg.check("input[value=no_water]"); pg.click("dialog button[value=ok]"); pg.wait_for_timeout(700)
    check("reject ran nothing", len(api("/api/commands")) == n0 + 1)
    pg.click("[data-tab=history]"); pg.wait_for_selector("text=Pump runs")
    h = pg.inner_text("#view")
    check("history shows approved run and declined advice", "You approved" in h and "Declined" in h)
    pg.screenshot(path=OUT + "07_history.png", full_page=True)
    pg.click("[data-tab=sensors]"); pg.wait_for_selector("text=Water used in the root zone")
    check("sensor chart drawn", pg.locator(".chart svg path").count() >= 2)
    pg.screenshot(path=OUT + "08_sensors.png", full_page=True)
    pg.click("[data-tab=settings]"); pg.wait_for_selector("#fsBtn")
    pg.click("#fsBtn"); pg.wait_for_selector("dialog[open]"); pg.fill("#c", "yes"); pg.click("dialog button[value=ok]"); pg.wait_for_timeout(500)
    check("fail-safe refuses without ARM", "ARM" in pg.inner_text("dialog .err"))
    pg.fill("#c", "arm"); pg.click("dialog button[value=ok]"); pg.wait_for_timeout(700)
    check("fail-safe armed after typing ARM", api("/api/status")["failsafe"]["armed"] is True)
    pg.screenshot(path=OUT + "09_settings.png", full_page=True)
    pg.click("#fsBtn"); pg.wait_for_timeout(600)
    check("fail-safe disarmed", api("/api/status")["failsafe"]["armed"] is False)
    # question flow from a clean profile is covered in the API tests; demo mode:
    pg.click("#toggleDemo"); pg.wait_for_selector("text=Simulation")
    pg.click("#nextAdvice"); pg.wait_for_selector("text=Today's advice")
    check("demo mode reaches an irrigate advice", "Irrigate" in pg.inner_text(".hero"))
    pg.click("[data-go=advice]"); pg.wait_for_selector("[data-act=modify]")
    pg.click("[data-act=modify]"); pg.fill("#mm", "500"); pg.click("dialog button[value=ok]"); pg.wait_for_timeout(300)
    check("demo refuses an amount above the cap (dialog stays open)", pg.is_visible("dialog[open]"))
    pg.fill("#mm", "30"); pg.click("dialog button[value=ok]"); pg.wait_for_selector("#toast:not([hidden])")
    check("demo records a modified run", "30 mm" in pg.inner_text("#toast"))
    pg.screenshot(path=OUT + "10_demo.png")
    # dark mode render
    ctx2 = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2, color_scheme="dark")
    pg2 = ctx2.new_page(); pg2.goto(BASE + "/"); pg2.wait_for_selector("#demoBtn"); pg2.click("#demoBtn"); pg2.wait_for_selector("text=Root-zone water")
    pg2.screenshot(path=OUT + "11_dark.png", full_page=True)
    b.close()
check("no JavaScript exceptions", not errs, "; ".join(errs[:3]))
print(f"\n{sum(1 for _, c in ok if c)} of {len(ok)} UI checks passed")
